### PR TITLE
fix: support webp property in wechat-miniprogram & change previousValue to pureDataPattern in rax-textinput

### PR DESCRIPTION
**Pull request by StKelen**
When gives a remote webp image source to image tag in wechat miniprogram, the webp property should set to true, ohterwise the image can't be shown in some iOS devices. This PR enable set webp property in rax-image.

Wechat MIniProgram's custom component enable an option called '[pureDataPattern](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/pure-data.html)'. Since previousValue in rax-textinput is not used in render, the property can change to pureDataProperty to reduce rerender counts. This PR change it to pureDataProperty.

### CODE REVIEW

**Review by ChrisCindy — COMMENTED** [review]
补充一下 ChangeLog，修改 package.json 的 version

**Comment by StKelen** [comment]
已更新~

**Review by ChrisCindy — APPROVED** [review]

**Review by cryzzchen — APPROVED** [review]

**Comment by ChrisCindy** [comment]
> 已更新~

package.json 的 version 没有修改

**Comment by StKelen** [comment]
> > 已更新~
> 
> package.json 的 version 没有修改

已更新✅

**Pull request merged**
